### PR TITLE
[MGDSTRM-10786] Disable java-operator-sdk controller metrics by default

### PR DESCRIPTION
**Pull request by MikeEdgar**

### CODE REVIEW

**Comment by rareddy** [comment]
what is the effect of this on any metrics that we may be capturing from this endpoint for management purposes?

**Comment by MikeEdgar** [comment]
> what is the effect of this on any metrics that we may be capturing from this endpoint for management purposes?

The operator will no longer store or return metrics in the `operator_sdk_` prefix. I haven't found anywhere they are actually used for anything currently.

**Review by rareddy — APPROVED** [review]
lgtm

**Review by biswassri — APPROVED** [review]
LGTM

**Review by shawkins — APPROVED** [review]
LGTM

**Pull request merged**
