### PR TITLE
Make OAuth clientId and clientSecret optional

### PR DESCRIPTION
**Pull request by MikeEdgar**
MGDSTRM-7968

Signed-off-by: Michael Edgar <medgar@redhat.com>

### CODE REVIEW

**Comment by MikeEdgar** [comment]
@biswassri FYI this impacts the changes you are making to remove the secrets from the ManagedKafka resource.

**Comment by biswassri** [comment]
> Yes, with your PR (once this is merged in) it will need to check for the presence of the secret references since the secret value will always be null in the operator.

Right! Makes sense. I'll include that as well.

**Comment by MikeEdgar** [comment]
> For the existing CRs, will it remove the configured clientid/secret? or it will only impact the new Kafka request?

This change only allows the clientid/secret to be unspecified in the CR. Existing CRs would need to have them removed in the control plane.

**Comment by akoserwal** [comment]
@MikeEdgar thanks

**Review by vbusch — APPROVED** [review]
lgtm

**Pull request merged**
