### PR TITLE
MGDSTRM-10985 accounting for the possibility of competing operators

### PR DESCRIPTION
**Pull request by shawkins**
With later josdk we'll likely enable leader election.

### CODE REVIEW

**Comment by MikeEdgar** [comment]
Can we use `io.javaoperatorsdk.operator.api.config.LeaderElectionConfiguration` even with the current platform?

**Comment by shawkins** [comment]
> Can we use io.javaoperatorsdk.operator.api.config.LeaderElectionConfiguration even with the current platform?

There have been a lot of fixes / improvements in the leader election logic since 5.12.4, I'm honestly not sure if a 5.x version is appropriate for general use - I was just going to wait until we were on a later version.

**Comment by MikeEdgar** [comment]
Ok, got it. I didn't realize it might not be ready.

**Review by MikeEdgar — APPROVED** [review]
lgtm

**Review by rareddy — APPROVED** [review]
lgtm

**Pull request merged**
