### PR TITLE
Configure Renovate

### PR DESCRIPTION
**Pull request by bf2robot**
Welcome to [Renovate](https://togithub.com/renovatebot/renovate)! This is an onboarding PR to help you understand and configure settings before regular Pull Requests begin.

🚦 To activate Renovate, merge this Pull Request. To disable Renovate, simply close this Pull Request unmerged.

---
### Detected Package Files

 * `.github/workflows/auto-labeler.yaml` (github-actions)
 * `.github/workflows/build.yml` (github-actions)
 * `.github/workflows/pre-release.yml` (github-actions)
 * `.github/workflows/release.yml` (github-actions)
 * `.github/workflows/smoke.yaml` (github-actions)
 * `.github/workflows/sonar.yml` (github-actions)
 * `.github/workflows/test.yaml` (github-actions)
 * `api/pom.xml` (maven)
 * `common/pom.xml` (maven)
 * `operator/pom.xml` (maven)
 * `perf/pom.xml` (maven)
 * `pom.xml` (maven)
 * `sync/pom.xml` (maven)
 * `systemtest/pom.xml` (maven)
 * `test/pom.xml` (maven)

### What to Expect

With your current configuration, Renovate will create 25 Pull Requests:

<details>
<summary>Update actions/github-script action to v3.1.1</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/actions-github-script-3.x`
  - Merge into: `main`
  - Upgrade [actions/github-script](https://togithub.com/actions/github-script) to `v3.1.1`

</details>

<details>
<summary>Update dependency com.google.code.findbugs:annotations to v3.0.1u2</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/findbugs.annotations.version`
  - Merge into: `main`
  - Upgrade [com.google.code.findbugs:annotations](https://togithub.com/findbugsproject/findbugs) to `3.0.1u2`

</details>

<details>
<summary>Update dependency org.projectlombok:lombok to v1.18.24</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/lombok.version`
  - Merge into: `main`
  - Upgrade [org.projectlombok:lombok](https://togithub.com/projectlombok/lombok) to `1.18.24`

</details>

<details>
<summary>Update fabric8.client.version to v5.12.4</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/fabric8.client.version`
  - Merge into: `main`
  - Upgrade [io.fabric8:openshift-model-operatorhub](https://togithub.com/fabric8io/kubernetes-client) to `5.12.4`
  - Upgrade [io.fabric8:kubernetes-client-bom](https://togithub.com/fabric8io/kubernetes-client) to `5.12.4`

</details>

<details>
<summary>Update dependency io.quarkus:quarkus-junit5 to v2.15.3.Final</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/quarkus.platform.test.version`
  - Merge into: `main`
  - Upgrade [io.quarkus:quarkus-junit5](https://togithub.com/quarkusio/quarkus) to `2.15.3.Final`

</details>

<details>
<summary>Update dependency io.strimzi:api to v0.32.0</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/strimzi.version`
  - Merge into: `main`
  - Upgrade [io.strimzi:api](https://togithub.com/strimzi/strimzi-kafka-operator) to `0.32.0`

</details>

<details>
<summary>Update dependency io.sundr:builder-annotations to v0.93.2</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/sundrio.version`
  - Merge into: `main`
  - Upgrade [io.sundr:builder-annotations](https://togithub.com/sundrio/sundrio) to `0.93.2`

</details>

<details>
<summary>Update dependency net.revelc.code:impsort-maven-plugin to v1.8.0</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/impsort-plugin.version`
  - Merge into: `main`
  - Upgrade [net.revelc.code:impsort-maven-plugin](https://togithub.com/revelc/impsort-maven-plugin) to `1.8.0`

</details>

<details>
<summary>Update dependency org.codehaus.mojo:build-helper-maven-plugin to v3.3.0</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/buildhelper-plugin.version`
  - Merge into: `main`
  - Upgrade [org.codehaus.mojo:build-helper-maven-plugin](https://togithub.com/mojohaus/build-helper-maven-plugin) to `3.3.0`

</details>

<details>
<summary>Update dependency org.codehaus.mojo:properties-maven-plugin to v1.1.0</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/properties-plugin.version`
  - Merge into: `main`
  - Upgrade [org.codehaus.mojo:properties-maven-plugin](https://togithub.com/mojohaus/properties-maven-plugin) to `1.1.0`

</details>

<details>
<summary>Update dependency org.yaml:snakeyaml to v1.33</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/snakeyaml.version`
  - Merge into: `main`
  - Upgrade [org.yaml:snakeyaml](https://bitbucket.org/snakeyaml/snakeyaml/src) to `1.33`

</details>

<details>
<summary>Update log4j.version to v2.19.0</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/log4j.version`
  - Merge into: `main`
  - Upgrade [org.apache.logging.log4j:log4j-slf4j-impl](https://gitbox.apache.org/repos/asf?p=logging-log4j2.git) to `2.19.0`
  - Upgrade [org.apache.logging.log4j:log4j-api](https://gitbox.apache.org/repos/asf?p=logging-log4j2.git) to `2.19.0`
  - Upgrade [org.apache.logging.log4j:log4j-core](https://gitbox.apache.org/repos/asf?p=logging-log4j2.git) to `2.19.0`

</details>

<details>
<summary>Update manusa/actions-setup-minikube action to v2.7.2</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/manusa-actions-setup-minikube-2.x`
  - Merge into: `main`
  - Upgrade [manusa/actions-setup-minikube](https://togithub.com/manusa/actions-setup-minikube) to `v2.7.2`

</details>

<details>
<summary>Update quarkus.platform.version to v2.15.3.Final</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/quarkus.platform.version`
  - Merge into: `main`
  - Upgrade [io.quarkus:quarkus-maven-plugin](https://togithub.com/quarkusio/quarkus) to `2.15.3.Final`
  - Upgrade [io.quarkus:quarkus-quartz](https://togithub.com/quarkusio/quarkus) to `2.15.3.Final`
  - Upgrade [io.quarkus:quarkus-arc](https://togithub.com/quarkusio/quarkus) to `2.15.3.Final`
  - Upgrade [io.quarkus:quarkus-micrometer-registry-prometheus](https://togithub.com/quarkusio/quarkus) to `2.15.3.Final`
  - Upgrade [io.quarkus:quarkus-openshift-client](https://togithub.com/quarkusio/quarkus) to `2.15.3.Final`
  - Upgrade [io.quarkus:quarkus-kubernetes-client](https://togithub.com/quarkusio/quarkus) to `2.15.3.Final`
  - Upgrade [io.quarkus:quarkus-bom](https://togithub.com/quarkusio/quarkus) to `2.15.3.Final`

</details>

<details>
<summary>Update styfle/cancel-workflow-action action to v0.11.0</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/styfle-cancel-workflow-action-0.x`
  - Merge into: `main`
  - Upgrade [styfle/cancel-workflow-action](https://togithub.com/styfle/cancel-workflow-action) to `0.11.0`

</details>

<details>
<summary>Update actions/cache action to v3</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/actions-cache-3.x`
  - Merge into: `main`
  - Upgrade [actions/cache](https://togithub.com/actions/cache) to `v3`

</details>

<details>
<summary>Update actions/checkout action to v3</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/actions-checkout-3.x`
  - Merge into: `main`
  - Upgrade [actions/checkout](https://togithub.com/actions/checkout) to `v3`

</details>

<details>
<summary>Update actions/github-script action to v6</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/actions-github-script-6.x`
  - Merge into: `main`
  - Upgrade [actions/github-script](https://togithub.com/actions/github-script) to `v6.3.3`

</details>

<details>
<summary>Update actions/labeler action to v4</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/actions-labeler-4.x`
  - Merge into: `main`
  - Upgrade [actions/labeler](https://togithub.com/actions/labeler) to `v4`

</details>

<details>
<summary>Update actions/setup-java action to v3</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/actions-setup-java-3.x`
  - Merge into: `main`
  - Upgrade [actions/setup-java](https://togithub.com/actions/setup-java) to `v3`

</details>

<details>
<summary>Update actions/upload-artifact action to v3</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/actions-upload-artifact-3.x`
  - Merge into: `main`
  - Upgrade [actions/upload-artifact](https://togithub.com/actions/upload-artifact) to `v3`

</details>

<details>
<summary>Update dependency io.quarkiverse.operatorsdk:quarkus-operator-sdk to v5</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/major-quarkus.operator.extension`
  - Merge into: `main`
  - Upgrade [io.quarkiverse.operatorsdk:quarkus-operator-sdk](https://togithub.com/quarkiverse/quarkiverse-parent) to `5.0.2`

</details>

<details>
<summary>Update dependency jakarta.validation:jakarta.validation-api to v3</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/major-jakarta.validation.version`
  - Merge into: `main`
  - Upgrade [jakarta.validation:jakarta.validation-api](https://togithub.com/eclipse-ee4j/beanvalidation-api) to `3.0.2`

</details>

<details>
<summary>Update dependency org.basepom:basepom-oss to v51</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/org.basepom-basepom-oss-51.x`
  - Merge into: `main`
  - Upgrade org.basepom:basepom-oss to `51`

</details>

<details>
<summary>Update fabric8.client.version to v6 (major)</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/major-fabric8.client.version`
  - Merge into: `main`
  - Upgrade [io.fabric8:openshift-model-operatorhub](https://togithub.com/fabric8io/kubernetes-client) to `6.3.1`
  - Upgrade [io.fabric8:kubernetes-client-bom](https://togithub.com/fabric8io/kubernetes-client) to `6.3.1`

</details>

---

### ⚠ Dependency Lookup Warnings ⚠

Please correct - or verify that you can safely ignore - these lookup failures before you merge this PR.

-   `Failed to look up maven dependency org.bf2:kas-fleetshard`
-   `Failed to look up maven dependency org.bf2:kas-fleetshard-operator`
-   `Failed to look up maven dependency org.bf2:test`
-   `Failed to look up maven dependency org.bf2:systemtest`
-   `Failed to look up maven dependency io.fabric8:openshift-model-common`
-   `Failed to look up maven dependency org.junit.jupiter:junit-jupiter-launcher`

Files affected: `api/pom.xml`, `common/pom.xml`, `operator/pom.xml`, `perf/pom.xml`, `pom.xml`, `sync/pom.xml`, `systemtest/pom.xml`, `test/pom.xml`

---

❓ Got questions? Check out Renovate's [Docs](https://docs.renovatebot.com/), particularly the Getting Started section.
If you need any further assistance then you can also [request help here](https://togithub.com/renovatebot/renovate/discussions).

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by daveconde** [comment]
Yea it'd be nice to get this enabled soon :)

**Review by shawkins — APPROVED** [review]
LGTM - we can further tweak the quarkus, basepom, and jib image rules as needed.

**Comment by kornys** [comment]
question is, do we want to enable renovate pipeline in jenkins after this merge?

**Comment by MikeEdgar** [comment]
> question is, do we want to enable renovate pipeline in jenkins after this merge?

Would it differ from what GitHub will be doing or just duplicate it?

**Comment by kornys** [comment]
It is a good question, I guess renovate can run in GH action so we dont need to run it from jenkins. wdyt @daveconde

**Review by MikeEdgar — APPROVED** [review]

**Pull request merged**
