### PR TITLE
MGDSTRM-11101 delaying the creation of ingresscontrollers

### PR DESCRIPTION
**Pull request by shawkins**
Delays the creation of ingresscontrollers until after we have a kafka.  A delayCreate member was added to simplify keeping the existing test logic with the same expectations, rather than adding dummy kafkas.

### CODE REVIEW

**Review by MikeEdgar — APPROVED** [review]
Looks good to me.

Do you think we should also consider (in a separate task/PR) the case where the last Kafka is deleted and the ICs are unused? I was thinking we could remove them then or, at worst, when the operator is uninstalled.

**Comment by shawkins** [comment]
> Do you think we should also consider (in a separate task/PR) the case where the last Kafka is deleted and the ICs are unused?

I was hoping to have clarity on the public kafka on private rosa scenario before making a change like that.

**Comment by shawkins** [comment]
@grdryn @k-wall can someone from kafka integrations comment on delaying the creation of the ingress controllers https://issues.redhat.com/browse/MGDSTRM-11101

**Review by grdryn — APPROVED** [review]
Looks reasonable to me, thanks :+1:

**Pull request closed without merging**
